// <auto-generated />
namespace ServiceManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class spareparttableisdeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spareparttableisdeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161250192_sparepart-table-isdeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
