// <auto-generated />
namespace ServiceManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class correttoisdeletedflag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correttoisdeletedflag));
        
        string IMigrationMetadata.Id
        {
            get { return "202011111154579_corretto-isdeleted-flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
