//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagement.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceManagement.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 400, (Bad Request). Пожалуйста, свяжитесь с вашим администратором..
        /// </summary>
        public static string BadRequest400 {
            get {
                return ResourceManager.GetString("BadRequest400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 404, Запись Не Найдена. Пожалуйста, свяжитесь с вашим администратором..
        /// </summary>
        public static string BadRequest404 {
            get {
                return ResourceManager.GetString("BadRequest404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здание.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип клиента.
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма собственности.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактное лицо.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция прошла успешно!.
        /// </summary>
        public static string DoneOk {
            get {
                return ResourceManager.GetString("DoneOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по названию компании.
        /// </summary>
        public static string FindByCompanyName {
            get {
                return ResourceManager.GetString("FindByCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по имени или фамилии.
        /// </summary>
        public static string FindByStaff {
            get {
                return ResourceManager.GetString("FindByStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс кода.
        /// </summary>
        public static string IndexCode {
            get {
                return ResourceManager.GetString("IndexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление данных.
        /// </summary>
        public static string LogDtUpd {
            get {
                return ResourceManager.GetString("LogDtUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор Таблицы.
        /// </summary>
        public static string LogIdTable {
            get {
                return ResourceManager.GetString("LogIdTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя Таблицы.
        /// </summary>
        public static string LogTableName {
            get {
                return ResourceManager.GetString("LogTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип Журнала.
        /// </summary>
        public static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string LogUsrUpd {
            get {
                return ResourceManager.GetString("LogUsrUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст слишком длинный.
        /// </summary>
        public static string MaxTextFieldLenght {
            get {
                return ResourceManager.GetString("MaxTextFieldLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить это?.
        /// </summary>
        public static string MsgDeleteGeneric {
            get {
                return ResourceManager.GetString("MsgDeleteGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что удалите файл журнала?.
        /// </summary>
        public static string MsgDeleteLog {
            get {
                return ResourceManager.GetString("MsgDeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное название компании.
        /// </summary>
        public static string MsgMandatoryCompanyName {
            get {
                return ResourceManager.GetString("MsgMandatoryCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное Контактное лицо.
        /// </summary>
        public static string MsgMandatoryContact {
            get {
                return ResourceManager.GetString("MsgMandatoryContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное имя клиента.
        /// </summary>
        public static string MsgMandatoryName {
            get {
                return ResourceManager.GetString("MsgMandatoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательная фамилия клиента.
        /// </summary>
        public static string MsgMandatorySurname {
            get {
                return ResourceManager.GetString("MsgMandatorySurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronimic {
            get {
                return ResourceManager.GetString("Patronimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код Изделия.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный Номер.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия .
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона не действителен.
        /// </summary>
        public static string TelephoneNotValid {
            get {
                return ResourceManager.GetString("TelephoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь отключен.
        /// </summary>
        public static string UserLoggedOut {
            get {
                return ResourceManager.GetString("UserLoggedOut", resourceCulture);
            }
        }
    }
}
